### ISSUE TITLE
communication error

### ISSUE THREAD

**Issue by 250Gamer** [enjoyneering/DFPlayer#1]
i use the esp32
conect with pin12 and pin14 as rx and tx
but it cant work
![Snipaste_2022-06-18_20-28-06](https://user-images.githubusercontent.com/106938524/174437665-ef26a125-1310-40cd-b3d9-b03de880ec1b.jpg)

**Comment by enjoyneering** [comment]
please, check this - https://stackoverflow.com/questions/60094545/esp32-softwareserial-library

**Comment by enjoyneering** [comment]
also do not forget that in arduino GPIO pin 12 and D12 are different pins.
