### ISSUE TITLE
HW-247A ... communication error

### ISSUE THREAD

**Issue by pploume** [enjoyneering/DFPlayer#3]
Hi,
Thanks for your work ... but unfortunately it doesn't work for me

I just buy on AliE some "DF Player mini" labelled HW-247A with the GB3200B chip.
It doesn't lool exactly as the one shown on your page (no STBY->BUSY nor STBY->GND solder points)

On ESP32, I've tryied the different module types, with timeout up to 2000ms ... still having communication error (#4)

Any suggestion or ideas to test ?

I can provide one module for testing if you want ...
the AE url is : https://www.aliexpress.com/item/1005001417104130.html?spm=a2g0o.order_list.0.0.30ba5e5bVI3RBV

thanks for your help

**Comment by enjoyneering** [comment]
The mode for HW-247A is [here](https://github.com/enjoyneering/DFPlayer/blob/main/images/DFPlayer_GD3200_Modification.jpg). You need it if you want to get rid of noise in the pause.

For HW-247A (GB3200B) you need to replace DFPLAYER_MINI with DFPLAYER_HW_247A

`mp3.begin(mp3Serial, MP3_SERIAL_TIMEOUT, DFPLAYER_HW_247A, false)`

**Comment by pploume** [comment]
Hi,

Thanks for your response.

I did as you mentioned on your site ... and in your mail.
No serial communication.

pm

**Comment by enjoyneering** [comment]
Hi, pploume

I got the GB3200B and fixed the library. Please try v.3.0.0 (see DFPlayer_ESP8266_GD3200B_Basic.ino for details)
